### ISSUE TITLE
output font size change, or width change? 

### ISSUE THREAD

**Issue by xiangao** [Hemken/Statamarkdown#34]
How to change the font size in output?  Currently the output always folds because it exceeds the width.  See the example:

reg mpg price

      Source |       SS           df       MS      Number of obs 
>   =        74
-------------+----------------------------------   F(1, 72)      
>   =     20.26
       Model |  536.541807         1  536.541807   Prob > F      
>   =    0.0000
    Residual |  1906.91765        72  26.4849674   R-squared     
>   =    0.2196
-------------+----------------------------------   Adj R-squared 
>   =    0.2087
       Total |  2443.45946        73  33.4720474   Root MSE      
>   =    5.1464

-----------------------------------------------------------------
> -------------
         mpg | Coefficient  Std. err.      t    P>|t|     [95% co
> n                                                              
>  f. interval]
-------------+---------------------------------------------------
> -------------
       price |  -.0009192   .0002042    -4.50   0.000    -.001326
> 3                                                              
>     -.0005121
       _cons |   26.96417   1.393952    19.34   0.000     24.1853
> 8                                                              
>      29.74297
-----------------------------------------------------------------
> -------------

**Comment by remlapmot** [comment]
Which output format are you rendering to: `html_document`, or `pdf_document` or `word_document` or something else?

The easiest way to achieve this for `pdf_document` is to set the `fontsize` option in the YAML header to say `10pt`, e.g.

````rmarkdown
---
title: "Make pdf font smaller"
author: "Name"
date: "2023-03-14"
output: pdf_document
fontsize: 10pt
---

```{r message=FALSE}
library(Statamarkdown)
```

```{stata}
sysuse auto, clear
regress mpg price
```
````

**Comment by remlapmot** [comment]
For HTML output you can change the font size using CSS, e.g. here the `body` font is the normal text in the document and the `pre` font is for the code chunks.

````rmarkdown
---
title: "Some HTML settings"
output: html_document
---

```{css echo=FALSE}
body {
  font-size: 10px;
}

pre {
  font-size: 10px;
}
```

```{r message=FALSE}
library(Statamarkdown)
```

Some normal/body text.

```{stata}
* Some pre text
sysuse auto, clear
reg mpg price
```
````

**Comment by Hemken** [comment]
Xiangoa,

You might also need to think about your linesize setting in Stata.  You can type

```
display c(linesize)
```

In Stata.  I think you want to set a wider margin in Stata.

Doug Hemken

Statistical consultant
Social Science Computing Cooperative
Univ. of Wisc. – Madison

***@***.******@***.***>
608-262-4327

From: xiangao ***@***.***>
Sent: Monday, March 13, 2023 8:08 PM
To: Hemken/Statamarkdown ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hemken/Statamarkdown] output font size change, or width change? (Issue #34)


How to change the font size in output? Currently the output always folds because it exceeds the width. See the example:

reg mpg price

  Source |       SS           df       MS      Number of obs

= 74
-------------+---------------------------------- F(1, 72)
= 20.26
Model | 536.541807 1 536.541807 Prob > F
= 0.0000
Residual | 1906.91765 72 26.4849674 R-squared
= 0.2196
-------------+---------------------------------- Adj R-squared
= 0.2087
Total | 2443.45946 73 33.4720474 Root MSE
= 5.1464

________________________________
________________________________

     mpg | Coefficient  Std. err.      t    P>|t|     [95% co

n
f. interval]
-------------+---------------------------------------------------

   price |  -.0009192   .0002042    -4.50   0.000    -.001326

3
-.0005121
_cons | 26.96417 1.393952 19.34 0.000 24.1853
8
29.74297

________________________________
________________________________

**Comment by xiangao** [comment]
Thank you, Tom and Doug!  "set linesize 96" works for me.  Good to know these tricks!
