### ISSUE TITLE
Unexpected Output

### ISSUE THREAD

**Issue by jules-bec** [Hemken/Statamarkdown#37]
Hello everyone, dear Mr. Hemken,

I am having issues with the output of the following codechunk:

```{stata graphbox01, echo = c(1:3), cleanlog=TRUE}
graph box income, ///
  over(state, sort(income) label(angle(65))) ///
  by(sex)
quietly graph export img/graphbox01.pdf, replace
```

As you can see below, the second and third code lines are repeated in the classical stata output style, despite having the cleanlong-option set to TRUE.
![output_issue](https://user-images.githubusercontent.com/122894978/236906713-6d0a9a17-e94b-4682-a318-c268906f3d53.png)

I suspect some issue with spreading the command syntax over several lines using the three slash signs, because this error does not occur when I write the command syntax in just one line.

This Code:

```{stata graphbox01, echo = 1, cleanlog=TRUE}
graph box income, over(state, sort(income) label(angle(65))) by(sex)
quietly graph export img/graphbox01.pdf, replace
```

produces just one line of code in the output and does not repeat it using the stata output style, which is what I also want to achieve while still using the three slashes to distribute the code syntax over several lines.
![grafik](https://user-images.githubusercontent.com/122894978/236908260-561328e6-d371-48bc-96af-b7065a43be3d.png)

Any help with this issue would be greately appreciated!

Kind regards,
Julien

**Comment by Hemken** [comment]
Julien, thanks for pointing that out.  I don’t think I’ve given any thought to those sort of continuations (even though I use them all the time in ordinary Stata coding, myself).  I’ll have a look.

Doug Hemken

Statistical consultant
Social Science Computing Cooperative
Univ. of Wisc. – Madison

***@***.******@***.***>
608-262-4327

From: jules-bec ***@***.***>
Sent: Monday, May 8, 2023 2:00 PM
To: Hemken/Statamarkdown ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hemken/Statamarkdown] Unexpected Output (Issue #37)


Hello everyone, dear Mr. Hemken,

I am having issues with the output of the following codechunk:

graph box income, ///

  over(state, sort(income) label(angle(65))) ///

  by(sex)

quietly graph export img/graphbox01.pdf, replace

As you can see below, the second and third code lines are repeated in the classical stata output style, despite having the cleanlong-option set to TRUE.
[Image removed by sender. output_issue]<https://user-images.githubusercontent.com/122894978/236906713-6d0a9a17-e94b-4682-a318-c268906f3d53.png>

I suspect some issue with spreading the command syntax over several lines using the three slash signs, because this error does not occur when I write the command syntax in just one line.

This Code:

graph box income, over(state, sort(income) label(angle(65))) by(sex)

quietly graph export img/graphbox01.pdf, replace

produces just one line of code in the output and does not repeat it using the stata output style, which is what I also want to achieve while still using the three slashes to distribute the code syntax over several lines.
[Image removed by sender. grafik]<https://user-images.githubusercontent.com/122894978/236908260-561328e6-d371-48bc-96af-b7065a43be3d.png>

Any help with this issue would be greately appreciated!

Kind regards,
Julien

**Comment by jules-bec** [comment]
​Dear Mr. Hemken,

I use the  ‘1.42’ version of the knitr package and the ‘0.7.2’ version of the StataMarkdown package. I have sent you my rmd File and other relevant files via E-Mail to the adress that is provided on the staff page of the Center for Demography and Ecology of the University of Wisconsin-Madison. Let me know if the E-Mail didn't go through or if you need any further information.

Thanks a lot for your help and kind regards,
Julien

**Comment by Hemken** [comment]
Got it.

Doug Hemken

Statistical consultant
Social Science Computing Cooperative
Univ. of Wisc. – Madison

***@***.******@***.***>
608-262-4327

**Comment by Hemken** [comment]
Despite looking at all the files in the document pipeline - .rmd, .do, .log, .md, .tex, .pdf - I can't see the source of Julien's problem, nor can I reproduce it.
